site_name: ifk-smhi
copyright: Made by [https://ingenjorsarbeteforklimatet.se](Ingenjörsarbete för Klimatet)
repo_url: https://github.com/Ingenjorsarbete-For-Klimatet/smhi

nav:
- Home: index.md
- Reference: reference.md

watch:
- smhi

theme:
  name: material
  palette:
    scheme: default
    primary: black
    accent: light green
  language: en
  icon:
    repo: fontawesome/brands/git-alt

plugins:
- search
- mkdocstrings
