site_name: ifk-smhi

nav:
- Home: index.md
- Reference: reference.md

watch:
- smhi

theme:
  name: material
  palette:
    scheme: default
    primary: black
    accent: light green

plugins:
- search
- mkdocstrings
