# generated by datamodel-codegen:
#   filename:  https://opendata-download-metanalys.smhi.se/api/category/mesan2g/version/1/validtime.json
#   timestamp: 2024-03-24T20:37:10+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class DataModel(BaseModel):
    valid_time: List[str] = Field(..., alias="validTime")
