# generated by datamodel-codegen:
#   filename:  https://opendata-download-metanalys.smhi.se/api/category/mesan2g/version/1/parameter.json
#   timestamp: 2024-03-24T20:37:10+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class ParameterItem(BaseModel):
    name: str
    key: str
    level_type: str = Field(..., alias="levelType")
    level: int
    unit: str
    missing_value: int = Field(..., alias="missingValue")


class DataModel(BaseModel):
    parameter: List[ParameterItem]
