# generated by datamodel-codegen:
#   filename:  https://opendata-download-metanalys.smhi.se/api/category/mesan2g/version/1/approvedtime.json
#   timestamp: 2024-03-24T20:37:10+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class DataModel(BaseModel):
    approved_time: str = Field(..., alias="approvedTime")
    reference_time: str = Field(..., alias="referenceTime")
