# generated by datamodel-codegen:
#   filename:  https://opendata-download-metobs.smhi.se/api/version/1.0.json
#   timestamp: 2024-03-23T16:55:00+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class LinkItem(BaseModel):
    href: str
    rel: str
    type: str


class GeoBox(BaseModel):
    minLatitude: float
    minLongitude: float
    maxLatitude: float
    maxLongitude: float


class ResourceItem(BaseModel):
    key: str
    updated: int
    title: str
    summary: str
    link: List[LinkItem]
    unit: str
    geoBox: GeoBox


class ParameterModel(BaseModel):
    key: str
    updated: int
    title: str
    summary: str
    link: List[LinkItem]
    resource: List[ResourceItem]
