# generated by datamodel-codegen:
#   filename:  https://opendata-download-metobs.smhi.se/api.json
#   timestamp: 2024-03-23T21:07:52+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class MetobsVersionLinkItem(BaseModel):
    href: str
    rel: str
    type: str


class MetobsVersionItem(BaseModel):
    key: Optional[str] = None
    updated: Optional[int] = None
    title: str
    summary: str
    link: List[MetobsVersionLinkItem]


class MetobsVersionModel(BaseModel):
    key: Optional[str] = None
    updated: Optional[int] = None
    title: str
    summary: str
    link: List[MetobsVersionLinkItem]
    version: List[MetobsVersionItem]

    @property
    def data(self) -> List[MetobsVersionItem]:
        return self.version
