# generated by datamodel-codegen:
#   filename:  https://opendata-download-metobs.smhi.se/api.json
#   timestamp: 2024-03-23T21:07:52+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class LinkItem(BaseModel):
    href: str
    rel: str
    type: str


class VersionItem(BaseModel):
    key: str | None
    updated: int | None
    title: str
    summary: str
    link: List[LinkItem]


class VersionModel(BaseModel):
    key: str | None
    updated: int | None
    title: str
    summary: str
    link: List[LinkItem]
    version: List[VersionItem]
