# generated by datamodel-codegen:
#   filename:  https://opendata-download-metobs.smhi.se/api/version/1.0/parameter/1.json
#   timestamp: 2024-03-23T17:00:59+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class LinkItem(BaseModel):
    href: str
    rel: str
    type: str


class StationSetItem(BaseModel):
    key: str
    updated: int
    title: str
    summary: str
    link: List[LinkItem]


class StationItem(BaseModel):
    key: str
    updated: int
    title: str
    summary: str
    link: List[LinkItem]
    name: str
    owner: str
    ownerCategory: str
    measuringStations: str
    id: int
    height: float
    latitude: float
    longitude: float
    active: bool
    from_: int = Field(..., alias="from")
    to: int


class StationModel(BaseModel):
    key: str
    updated: int
    title: str
    summary: str
    unit: str
    valueType: str
    link: List[LinkItem]
    stationSet: List[StationSetItem]
    station: List[StationItem]
