# generated by datamodel-codegen:
#   filename:  https://opendata-download-metobs.smhi.se/api/version/1.0/parameter/1/station/1/period/corrected-archive.json
#   timestamp: 2024-03-23T21:07:54+00:00

from __future__ import annotations

from typing import List, Optional

import pandas as pd
from pydantic import BaseModel, ConfigDict, Field


class MetobsLinkItem(BaseModel):
    href: str
    rel: str
    type: str


class MetobsDatum(BaseModel):
    key: Optional[str] = None
    updated: Optional[int] = None
    title: str
    summary: str
    link: List[MetobsLinkItem]


class MetobsData(BaseModel):
    key: Optional[str] = None
    updated: Optional[int] = None
    title: str
    summary: str
    from_: int = Field(..., alias="from")
    to: int
    link: List[MetobsLinkItem]
    data: List[MetobsDatum]


class MetobsDataModel(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    station: Optional[pd.DataFrame] = None
    parameter: Optional[pd.DataFrame] = None
    period: Optional[pd.DataFrame] = None
    stationdata: Optional[pd.DataFrame] = None
